let shopItemsData = [
  {
    id: "perfume1",
    name: "Aqua di Luna",
    prices: { 30: 35, 50: 55, 100: 95 },
    desc: "Світлий, свіжий аромат з нотами цитрусу і зеленого чаю.",
    img: "images/img-1.jpg",
    category: "women",
  },
  {
    id: "perfume2",
    name: "Mystique Noir",
    prices: { 30: 40, 50: 60, 100: 100 },
    desc: "Темний, чуттєвий аромат з ванільними та деревними нотами.",
    img: "images/img-2.jpg",
    category: "women",
  },
  {
    id: "perfume3",
    name: "Jardin Sauvage",
    prices: { 30: 37, 50: 57, 100: 97 },
    desc: "Свіжий аромат з квітковими нотами жасмину і троянди.",
    img: "images/img-3.jpg",
    category: "women",
  },
  {
    id: "perfume4",
    name: "Bleu Essence",
    prices: { 30: 32, 50: 52, 100: 90 },
    desc: "Чистий і освіжаючий аромат з нотами морського бризу.",
    img: "images/img-4.jpg",
    category: "unisex",
  },
  {
    id: "perfume5",
    name: "Rose Reverie",
    prices: { 30: 25, 50: 45, 100: 85 },
    desc: "Ніжний аромат з нотами троянди та лаванди.",
    img: "images/img-5.jpg",
    category: "women",
  },
  {
    id: "perfume6",
    name: "Floral Essence",
    prices: { 30: 22, 50: 42, 100: 72 },
    desc: "Ніжний аромат з квітковими нотами жасмину, троянди та лілії.",
    img: "images/img-6.jpg",
    category: "women",
  },
  {
    id: "perfume7",
    name: "Silver Night",
    prices: { 30: 45, 50: 70, 100: 120 },
    desc: "Елегантний аромат з нотами чорного перцю та сандалового дерева.",
    img: "images/img-7.jpg",
    category: "women",
  },
  {
    id: "perfume8",
    name: "Vanilla Dream",
    prices: { 30: 20, 50: 35, 100: 60 },
    desc: "Теплий і солодкий аромат з ванільними нотами.",
    img: "images/img-8.jpg",
    category: "men",
  },
  {
    id: "perfume9",
    name: "Oceanic Wave",
    prices: { 30: 38, 50: 58, 100: 98 },
    desc: "Світлий і морський аромат з нотами океану і цитрусів.",
    img: "images/img-9.jpg",
    category: "unisex",
  },
  {
    id: "perfume10",
    name: "Midnight Spice",
    prices: { 30: 30, 50: 50, 100: 90 },
    desc: "Теплий і пряний аромат з нотами кориці та ванілі.",
    img: "images/img-10.jpg",
    category: "men",
  },
  {
    id: "perfume11",
    name: "Amber Glow",
    prices: { 30: 33, 50: 53, 100: 95 },
    desc: "Теплий аромат з нотами амбри, ванілі і карамелі.",
    img: "images/img-21.jpg",
    category: "women",
  },
  {
    id: "perfume12",
    name: "Sapphire Nights",
    prices: { 30: 40, 50: 65, 100: 110 },
    desc: "Складний, містичний аромат з нотами лаванди, пачулі і темного дерева.",
    img: "images/img-12.jpg",
    category: "unisex",
  },
  {
    id: "perfume13",
    name: "Golden Citrus",
    prices: { 30: 22, 50: 42, 100: 75 },
    desc: "Яскравий аромат з нотами апельсина, лимону і бергамоту.",
    img: "images/img-13.jpg",
    category: "unisex",
  },
  {
    id: "perfume14",
    name: "Royal Oud",
    prices: { 30: 55, 50: 85, 100: 160 },
    desc: "Розкішний аромат з нотами удового дерева, сандалу і спецій.",
    img: "images/img-14.jpg",
    category: "men",
  },
  {
    id: "perfume15",
    name: "Lily Breeze",
    prices: { 30: 25, 50: 45, 100: 75 },
    desc: "Квітковий аромат з нотами лілії, фрезії та жасмину.",
    img: "images/img-15.jpg",
    category: "women",
  },
  {
    id: "perfume16",
    name: "Mystic Woods",
    prices: { 30: 40, 50: 60, 100: 105 },
    desc: "Природний аромат з нотами хвойного лісу та деревини.",
    img: "images/img-16.jpg",
    category: "unisex",
  },
  {
    id: "perfume17",
    name: "Café Noir",
    prices: { 30: 28, 50: 48, 100: 80 },
    desc: "Теплий і глибокий аромат з нотами кави, шоколаду та ванілі.",
    img: "images/img-17.jpg",
    category: "men",
  },
  {
    id: "perfume18",
    name: "Tropical Blossom",
    prices: { 30: 35, 50: 55, 100: 90 },
    desc: "Тропічний аромат з нотами манго, кокоса та жасмину.",
    img: "images/img-18.jpg",
    category: "women",
  },
  {
    id: "perfume19",
    name: "Desert Rose",
    prices: { 30: 30, 50: 50, 100: 85 },
    desc: "Екзотичний аромат з нотами рози, сандалового дерева та спецій.",
    img: "images/img-19.jpg",
    category: "unisex",
  },
  {
    id: "perfume20",
    name: "Velvet Ember",
    prices: { 30: 38, 50: 58, 100: 95 },
    desc: "Теплий і загадковий аромат з нотами кориці, амбри та фіалки.",
    img: "images/img-20.jpg",
    category: "women",
  },
];
